/**
 * Three systems carried end to end: a support chatbot, a synthetic image
 * pipeline and an emotion-recognition kiosk. Each one goes from a profile to a
 * served response and the line of evidence it leaves behind. The other test
 * files check the pieces; this one checks that the pieces still add up to what
 * a deployment actually needs.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";

import {
  assess,
  disclose,
  requirements,
  withDisclosure,
  DISCLOSURE_HEADER,
  EvidenceLog,
  IncompleteDisclosure,
  RULES_VERSION,
  UnmarkedContent,
  type Entry,
  type SystemProfile,
} from "../src/index.ts";

/** Fixed, so an exported record is the same bytes on every run. */
const clock = () => {
  let tick = 0;
  return () => new Date(Date.UTC(2026, 7, 16, 12, 0, tick++));
};

const inputs = (entry: Entry) => entry.detail.inputs as Record<string, unknown>;
const applied = (entry: Entry) =>
  entry.detail.applies as { obligation: string; article: string; summary: string }[];

describe("a customer-support chatbot", () => {
  const profile: SystemProfile = { role: "provider", interactsWithPeople: true };
  const sentence = "You are chatting with our AI assistant, not a member of staff.";
  const notice = { locale: "en-GB", text: { "ai-system": sentence } };

  const handler = () =>
    new Response(JSON.stringify({ answer: "The office opens at nine." }), {
      headers: { "content-type": "application/json" },
    });

  test("one obligation, one element, and a deadline of the first interaction", () => {
    const assessment = assess(profile);
    assert.deepEqual(
      assessment.applies.map((a) => a.obligation.id),
      ["art50-1"],
    );
    assert.deepEqual(assessment.excluded, []);
    assert.deepEqual(assessment.needsReview, []);

    const [requirement] = requirements(profile);
    assert.equal(requirement.measure, "inform-before-interaction");
    assert.equal(requirement.satisfiedByText, true);
    assert.deepEqual(
      requirement.elements.map((element) => element.id),
      ["ai-system"],
    );
    assert.match(requirement.placement.when, /first interaction/);
  });

  test("the wording is the product's, and none of it may be left blank", () => {
    assert.throws(() => disclose(profile, { locale: "en-GB", text: {} }), IncompleteDisclosure);

    const disclosure = disclose(profile, notice);
    assert.equal(disclosure.statement, sentence);
    assert.deepEqual(disclosure.elements, ["ai-system"]);
    assert.deepEqual(disclosure.unmetByStatement, []);
  });

  test("a request comes back disclosed, and the log can show it did", async () => {
    const log = new EvidenceLog({ now: clock() });
    const wrapped = withDisclosure(handler, profile, {
      ...notice,
      log,
      injectJsonKey: "disclosure",
    });

    const response = await wrapped(new Request("https://example.com/chat"));
    assert.equal(response.headers.get(DISCLOSURE_HEADER), "art50-1");
    assert.deepEqual(await response.json(), {
      answer: "The office opens at nine.",
      disclosure: sentence,
    });

    const [decision, shown] = log.entries;
    assert.deepEqual(log.entries.map((entry) => entry.kind), ["assessment", "disclosure-shown"]);
    assert.equal(decision.rules, RULES_VERSION);
    assert.equal(inputs(decision).interactsWithPeople, true);
    // Nobody was asked about deep fakes here, and the record says that rather
    // than a no on the operator's behalf.
    assert.equal(inputs(decision).deepfake, "not stated");
    assert.deepEqual(applied(decision).map((a) => a.article), ["Article 50(1)"]);
    assert.match(applied(decision)[0].summary, /interacting with an AI system/);
    assert.equal(shown.detail.path, "/chat");
    assert.equal(shown.detail.statement, sentence);
    assert.equal(shown.detail.locale, "en-GB");
    assert.equal(log.verify().ok, true);
  });
});

describe("a synthetic image pipeline", () => {
  const profile: SystemProfile = { role: "both", generatesSyntheticContent: true, deepfake: true };
  const sentence = "This image was generated by AI and depicts a real place.";
  const notice = { locale: "en-GB", text: { "artificial-content": sentence } };
  const pixels = new Uint8Array([0x89, 0x50, 0x4e, 0x47]);

  const handler = () => new Response(pixels, { headers: { "content-type": "image/png" } });

  test("two duties, and only one of them can be met by saying something", () => {
    assert.deepEqual(
      requirements(profile).map((r) => r.measure),
      ["mark-machine-readable", "disclose-artificial-content"],
    );

    const [marking] = requirements(profile);
    assert.equal(marking.satisfiedByText, false);
    assert.deepEqual(marking.elements, []);
    assert.match(marking.placement.where, /inside the content/);

    const disclosure = disclose(profile, notice);
    assert.equal(disclosure.statement, sentence);
    assert.equal(disclosure.machineReadable[DISCLOSURE_HEADER], "art50-2, art50-4-deepfake");
    assert.deepEqual(disclosure.unmetByStatement, ["mark-machine-readable"]);
  });

  test("the image is served disclosed, unmarked, and the file says both", async () => {
    const log = new EvidenceLog({ now: clock() });
    const wrapped = withDisclosure(handler, profile, { ...notice, log });

    const response = await wrapped(new Request("https://example.com/render"));
    assert.equal(response.headers.get(DISCLOSURE_HEADER), "art50-2, art50-4-deepfake");
    assert.deepEqual(new Uint8Array(await response.arrayBuffer()), pixels);

    const result = await new UnmarkedContent().mark({ content: pixels, mediaType: "image/png" });
    assert.equal(result.marked, false);
    assert.equal(result.content, pixels);
    log.append("content-unmarked", {
      mediaType: "image/png",
      marker: "unmarked",
      method: result.method,
      detail: result.detail,
    });

    // The gap has to survive the export: a reader with the file and nothing
    // else must be able to see that nothing was ever marked.
    const file = log
      .toJSONL()
      .split("\n")
      .filter((line) => line !== "")
      .map((line) => JSON.parse(line) as Entry);

    assert.deepEqual(file.map((entry) => entry.kind), [
      "assessment",
      "disclosure-shown",
      "content-unmarked",
    ]);
    assert.deepEqual(file[0].detail.unmetByStatement, ["mark-machine-readable"]);
    assert.equal(file[2].detail.method, "none");
    assert.match(String(file[2].detail.detail), /not met by this deployment/);
    assert.equal(EvidenceLog.fromJSONL(log.toJSONL()).verify().ok, true);
  });
});

describe("an emotion-recognition kiosk", () => {
  const profile: SystemProfile = { role: "deployer", emotionRecognition: true };
  const aiSentence = "This kiosk is an AI system.";
  const biometricSentence = "It reads facial expressions to measure how the queue is feeling.";
  const notice = {
    locale: "en-GB",
    text: { "ai-system": aiSentence, "biometric-operation": biometricSentence },
  };

  const handler = () =>
    new Response("<p>Welcome</p>", { headers: { "content-type": "text/html" } });

  test("exposure takes two elements, and half a notice is refused", () => {
    const [requirement] = requirements(profile);
    assert.equal(requirement.measure, "inform-exposed-persons");
    assert.deepEqual(
      requirement.elements.map((element) => element.id),
      ["ai-system", "biometric-operation"],
    );
    assert.match(requirement.placement.when, /first exposure/);
    assert.match(requirement.placement.where, /not on a policy page/);

    assert.throws(
      () => disclose(profile, { locale: "en-GB", text: { "ai-system": aiSentence } }),
      (error: unknown) => {
        assert.ok(error instanceof IncompleteDisclosure);
        assert.deepEqual(
          error.missing.map((element) => element.id),
          ["biometric-operation"],
        );
        return true;
      },
    );
  });

  test("both sentences are shown together and recorded as shown", async () => {
    const log = new EvidenceLog({ now: clock() });
    const wrapped = withDisclosure(handler, profile, { ...notice, log });

    const response = await wrapped(new Request("https://example.com/kiosk"));
    assert.equal(response.headers.get(DISCLOSURE_HEADER), "art50-3");
    assert.equal(await response.text(), "<p>Welcome</p>");

    const [decision, shown] = log.entries;
    assert.deepEqual(decision.detail.elements, ["ai-system", "biometric-operation"]);
    assert.equal(inputs(decision).emotionRecognition, true);
    assert.equal(inputs(decision).biometricCategorisation, "not stated");
    assert.equal(shown.detail.statement, `${aiSentence} ${biometricSentence}`);
    assert.deepEqual(shown.detail.obligations, ["art50-3"]);
    assert.equal(log.verify().ok, true);
  });

  test("an authorised law-enforcement kiosk says nothing, and the record says why", async () => {
    const exempt: SystemProfile = { ...profile, lawEnforcementAuthorised: true };
    const log = new EvidenceLog({ now: clock() });
    const wrapped = withDisclosure(handler, exempt, { log });

    const response = await wrapped(new Request("https://example.com/kiosk"));
    assert.equal(response.headers.get(DISCLOSURE_HEADER), null);
    assert.equal(await response.text(), "<p>Welcome</p>");

    // Nothing was shown, so nothing is logged as shown — but the claim that
    // excused it is on the file, with the reason attached.
    assert.deepEqual(log.entries.map((entry) => entry.kind), ["assessment"]);
    const excluded = log.entries[0].detail.excluded as { obligation: string; because: string }[];
    assert.deepEqual(excluded.map((exclusion) => exclusion.obligation), ["art50-3"]);
    assert.match(excluded[0].because, /criminal offences/);
    assert.equal(inputs(log.entries[0]).lawEnforcementAuthorised, true);
    assert.equal(log.verify().ok, true);
  });
});
