/**
 * A run through the whole package: assess a system, learn what the notice has
 * to say, write it, serve one request with it attached, and check the record.
 *
 *   npm run demo
 */

import {
  assess,
  disclose,
  requirements,
  EvidenceLog,
  withDisclosure,
  type Notice,
  type SystemProfile,
} from "../src/index.ts";

// A support assistant that also generates images of real places for the user.
const profile: SystemProfile = {
  role: "both",
  interactsWithPeople: true,
  generatesSyntheticContent: true,
  deepfake: true,
};

const assessment = assess(profile);
console.log("Obligations that apply:");
for (const { obligation, note } of assessment.applies) {
  console.log(`  ${obligation.article.padEnd(16)} ${obligation.summary}`);
  if (note) console.log(`  ${" ".repeat(16)} note: ${note}`);
}

console.log("\nWhat the notice has to get across:");
const seen = new Set<string>();
for (const requirement of requirements(profile)) {
  for (const element of requirement.elements) {
    if (seen.has(element.id)) continue;
    seen.add(element.id);
    console.log(`  ${element.id.padEnd(20)} ${element.must}`);
  }
}

const notice: Notice = {
  locale: "en-GB",
  text: {
    "ai-system": "You are chatting with our AI assistant.",
    "artificial-content": "Images in this answer were generated by AI.",
  },
};

const disclosure = disclose(profile, notice);
console.log(`\nWhat the person is told (${disclosure.locale}):\n  "${disclosure.statement}"`);

if (disclosure.unmetByStatement.length > 0) {
  console.log("\nNot covered by saying it:");
  for (const measure of disclosure.unmetByStatement) {
    console.log(`  ${measure} — needs a marker; none is configured`);
  }
}

try {
  disclose(profile, { locale: "en-GB", text: { "ai-system": "You are chatting with our AI assistant." } });
} catch (error) {
  console.log(`\nA notice with an element left blank is refused:\n  ${(error as Error).message}`);
}

const log = new EvidenceLog();
const handler = withDisclosure(
  () => new Response(JSON.stringify({ answer: "The office opens at nine." }), {
    headers: { "content-type": "application/json" },
  }),
  profile,
  { ...notice, log, injectJsonKey: "disclosure" },
);

const response = await handler(new Request("https://example.com/chat"));
console.log("\nOne request through the middleware:");
console.log(`  AI-Disclosure: ${response.headers.get("AI-Disclosure")}`);
console.log(`  body: ${await response.text()}`);

console.log("\nEvidence log:");
for (const entry of log.entries) {
  console.log(`  #${entry.seq} ${entry.kind} ${entry.hash.slice(0, 12)}…`);
}
console.log(`  chain verifies: ${log.verify().ok}`);
