/**
 * Turning an assessment into the disclosure a person actually sees.
 *
 * Article 50(5) sets the bar for all of these: clear, distinguishable, and
 * given at the latest at the time of the first interaction or exposure. That is
 * why the disclosure is built once, up front, rather than appended to an answer
 * after the fact.
 */

import { assess, measures, type Assessment, type Measure, type SystemProfile } from "./policy.ts";

/**
 * The header this library sets. There is no standard header for this — the
 * regulation says what must be communicated, not how — so this is a convention
 * of this package. It is a machine-readable hint alongside the human-readable
 * statement, never a substitute for it.
 */
export const DISCLOSURE_HEADER = "AI-Disclosure";

export type Disclosure = {
  /** Shown to the person. Plain language, no jargon. */
  readonly statement: string;
  /** The obligations this disclosure exists to satisfy. */
  readonly obligations: readonly string[];
  /** Measures still unmet by a statement alone — marking, above all. */
  readonly unmetByStatement: readonly Measure[];
  /** For headers and metadata. */
  readonly machineReadable: Readonly<Record<string, string>>;
  /** Where the article keeps the duty but changes how it must be met. */
  readonly notes: readonly string[];
};

const STATEMENTS: Record<Measure, string> = {
  "inform-before-interaction": "You are interacting with an AI system.",
  "inform-exposed-persons":
    "This service uses an AI system that analyses biometric or emotional signals.",
  "disclose-artificial-content": "This content was generated or altered by an AI system.",
  "mark-machine-readable": "This content was generated by an AI system.",
};

export type DisclosureOptions = {
  /** Replace the wording, e.g. to match a product's voice or another language. */
  readonly statements?: Partial<Record<Measure, string>>;
};

/**
 * Build the disclosure for a profile.
 *
 * `unmetByStatement` is the honest part: telling someone in words that content
 * is AI-generated does not embed a machine-readable mark, and Article 50(2)
 * asks for both. A caller that ignores this field is not covered by the text it
 * just rendered.
 */
export function disclose(profile: SystemProfile, options: DisclosureOptions = {}): Disclosure {
  const assessment: Assessment = assess(profile);
  const required = measures(assessment);
  const wording = { ...STATEMENTS, ...options.statements };

  // A statement is spoken language; only these measures are satisfied by it.
  const spoken: Measure[] = [
    "inform-before-interaction",
    "inform-exposed-persons",
    "disclose-artificial-content",
  ];

  const lines = required
    .filter((measure) => spoken.includes(measure))
    .map((measure) => wording[measure]);

  const obligations = assessment.applies.map((a) => a.obligation.id);
  const notes = assessment.applies
    .filter((a) => a.note !== undefined)
    .map((a) => `${a.obligation.article}: ${a.note}`);

  const machineReadable: Record<string, string> = {};
  if (obligations.length > 0) {
    machineReadable[DISCLOSURE_HEADER] = obligations.join(", ");
  }

  return {
    statement: [...new Set(lines)].join(" "),
    obligations,
    unmetByStatement: required.filter((measure) => !spoken.includes(measure)),
    machineReadable,
    notes,
  };
}
